name:               "Park junhyuk"
description:        "수정중"

url:                "junhyuk93.github.io"
author:             "Park junhyuk"
email:              "akznsk1@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "akznsk1@gmail.com"
github:             "junhyuk93"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "waku"

background:         "https://avatars.githubusercontent.com/u/61610411?s=400&u=e0c34baac2dbd6cb74f26a4291f234332f950885&v=4"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate