# Setup
title: Junhyuk Park
description: AI Engineer / Data nalyst
url: https://Junhyuk93.github.io
avatar: /KakaoTalk_20220103_123627283.jpg
paginate: 10
permalink: pretty
cover_image: /캡처.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
logo: logo.png
social:
  name: Junhyuk Park
  links:
    - https://twitter.com/vszhub
    - https://github.com/junhyuk93
google_site_verification: xxxxx
lang: en / kr

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Junhyuk Park
  url: https://github.com/junhyuk93/
  email: akznsk1@gmail.com
