name:               "Park junhyuk"
description:        "수정중"

url:                "junhyuk93.github.io"
author:             "Data wakuwaku"
email:              "akznsk1@gmail.com"
gravatar_hash:      "https://img1.daumcdn.net/thumb/C120x120/?fname=https%3A%2F%2Ft1.daumcdn.net%2Fcafeattach%2FmEr9%2F920f1be01d06c16ed0fedbeb527dda4f2bc25bfb"
twitter:            ""
email:              "akznsk1@gmail.com"
github:             "junhyuk93"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "waku"

background:         "https://t1.daumcdn.net/cafeattach/mEr9/f1d4d63d8e7c1f5ec641cef83d0926cc257f965c"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate