name:               "Park junhyuk"
description:        "A minimalistic jekyll theme for humans"

url:                "junhyuk93.github.io"
author:             "Park junhyuk"
email:              "akznsk1@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "akznsk1@gmail.com"
github:             "https://github.com/Junhyuk93"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "waku"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate