name:               "Data wakuwaku"
description:        "성장하는 개발 블로그"

url:                "junhyuk93.github.io"
author:             "Park junhyuk"
email:              "akznsk1@gmail.com"
gravatar_hash:      "https://avatars.githubusercontent.com/u/61610411?v=4"
twitter:            ""
email:              "akznsk1@gmail.com"
github:             "junhyuk93"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "waku"

background:         "https://mblogthumb-phinf.pstatic.net/MjAxODAxMDRfMjE5/MDAxNTE1MDQyNTcwMzcy.PFUe5IbX0MkEGZ_k3uVAScSfqm9D0lyEa2-dat6XqyUg.eZhGs-ykzXlMFHhkcMKH_1OVGO9_Ta2niIDtSVs0jlgg.JPEG.ommmgo/image_5759837891515042555071.jpg?type=w800"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate